app/config/routes.rb
Rails.application.routes.draw do
    
    get 'solicituds/index', to: "solicituds#index"
    get 'solicituds/edit', to: "solicituds#edit"
    get 'solicituds/show', to: "solicituds#show"
    get 'solicituds/new', to: "solicituds#new"
    
    get 'servicios/index', to: "servicios#index"
    get 'servicios/edit', to: "servicios#edit"
    get 'servicios/show', to: "servicios#show"
    get 'servicios/new', to: "servicios#new"
    
    get 'huespeds/index', to: "huespeds#index"
    get 'huespeds/edit', to: "huespeds#edit"
    get 'huespeds/show', to: "huespeds#show"
    get 'huespeds/new', to: "huespeds#new"
    
    get 'empleados/index', to: "empleados#index"
    get 'empleados/edit', to: "empleados#edit"
    get 'empleados/show', to: "empleados#show"
    get 'empleados/new', to: "empleados#new"
    
    root 'pages#welcome'
    
    resources :huespeds
    resources :solicituds
    resources :servicios
    resources :empleados
    
end

app/app/models/empleado.rb
class Empleado < ApplicationRecord
    
end

app/app/models/empleados.rb
class Empleado < ApplicationRecord
    
end

app/app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController

    def new
        @empleado = Empleado.new
    end
    
    def create
         @empleado = Empleado.new(empleado_params)
        if @empleado.save
            flash[:notice] = "El empleado se creo satisfactoriamente"
            redirect_to empleado_path(@empleado)
        else
            render "new"
        end
    end
    
    def show 
        @empleado = Empleado.find(params[:id])
    end
    
    def edit
        @empleado= Empleado.find(params[:id])
    end 
    
    def update
        @empleado = Empleado.find(params[:id])
         if @empleado.update(empleado_params)
            flash[:notice] = "El Empleado se creo satisfactoriamente"
            redirect_to empleado_path(@empleado)
        else
            render "edit"
        end
    end
    
    def destroy
        @empleado = empleado.find(params[:id])
        @empeleado.destroy
        flash[:notice] = "El empleado se eliminó satisfactoriamente"
        redirect_to empleados_path
    end
    
    def index
        @empleados = Empleado.all
    end
    
    private 
        def empleado_params
         params.require(:empleado).permit(:nombres,:apellidos,:cedula,:celular)
        end 
end

app/app/views/empleados/edit.html.erb
<h1> Edicion Empleado! </h1>
<% if @empleado.errors.any? %>
  <% @empleado.errors.full_messages.each do |mensaje| %>
    <ul>
      <li> <%= mensaje %> </li>
    </ul>
  <% end %>
<% end %>

<%= form_for @empleado do |f| %>
  
    
    <p>
    <%= f.label :nombres %><br/>
    <%= f.text_field :nombres  %><br/>
    </p>
    
    <p>
    <%= f.label :apellidos %><br/>
    <%= f.text_field :apellidos  %><br/>
    </p>
    
    <p>
    <%= f.label :cedula %><br/>
    <%= f.number_field :cedula  %><br/>
    </p>
    
    <p>
    <%= f.label :celular %><br/>
    <%= f.number_field :celular  %><br/>
    </p>
           
    <p>
    <%= f.submit "Editar huesped" %><br/>
    </p>

   <%= link_to "Volver a indice de empleados", empleados_path %>
<% end %>

app/app/views/empleados/index.html.erb
<table>
  <tr>
    <th> ID Empleado </th><th> Nombres </th><th> Apellidos </th><th> Cedula </th><th> Celular </th>
  </tr>
  <% @empleados.each do |empleado| %>
  <tr>
    <td><%= empleado.id %></td><td><%= empleado.nombres %></td><td><%= empleado.apellidos %></td><td><%= empleado.cedula %></td><td><%= empleado.celular %></td>
    <td><%= link_to "Editar Empleado", edit_empleado_path(empleado.id) %> </td>
    <td><%= link_to "Mostrar Empleado", empleado_path(empleado) %></td>
    <td><%= link_to "Eliminar Empleado", empleado_path(empleado), method: :delete, data: {confirm: "Seguro?" } %></td>
  </tr>
  <% end %>
</table>

<%= link_to "Crear nuevo Empleado", new_empleado_path %>
<%= link_to "Pagina principal", root_path %>

app/app/views/empleados/new.html.erb
<% if @empleado.errors.any? %>
  <% @empleado.errors.full_messages.each do |mensaje| %>
    <ul>
      <li> <%= mensaje %> </li>
    </ul>
  <% end %>
<% end %>

<%= form_for @empleado do |f| %>
  
    
    <p>
    <%= f.label :nombres %><br/>
    <%= f.text_field :nombres  %><br/>
    </p>
    
    <p>
    <%= f.label :apellidos %><br/>
    <%= f.text_field :apellidos  %><br/>
    </p>
    
    <p>
    <%= f.label :cedula %><br/>
    <%= f.number_field :cedula  %><br/>
    </p>
    
    <p>
    <%= f.label :celular %><br/>
    <%= f.number_field :celular  %><br/>
    </p>
           
    <p>
    <%= f.submit "Editar huesped" %><br/>
    </p>

   <%= link_to "Volver a indice de empleados", empleados_path %>
<% end %>

app/app/views/empleados/show.html.erb
<h1>Empleado Creado</h1>
<p>
  Titulo: <%= @empleado.cedula %>
</p>
<p>
  Nombres: <%= @empleado.nombres %>
</p>
<p>
  Apellidos: <%= @empleado.apellidos %>
</p>


 <%= link_to "Volver a indice de empleados", empleado_path %>
 <%= link_to "Editar informacion de empleado", edit_empleado_path(@empleado.id) %>