app/config/routes.rb
Rails.application.routes.draw do
    
    get 'solicituds/index', to: "solicituds#index"
    get 'solicituds/edit', to: "solicituds#edit"
    get 'solicituds/show', to: "solicituds#show"
    get 'solicituds/new', to: "solicituds#new"
    
    get 'servicios/index', to: "servicios#index"
    get 'servicios/edit', to: "servicios#edit"
    get 'servicios/show', to: "servicios#show"
    get 'servicios/new', to: "servicios#new"
    
    get 'huespeds/index', to: "huespeds#index"
    get 'huespeds/edit', to: "huespeds#edit"
    get 'huespeds/show', to: "huespeds#show"
    get 'huespeds/new', to: "huespeds#new"
    
    get 'empleados/index', to: "empleados#index"
    get 'empleados/edit', to: "empleados#edit"
    get 'empleados/show', to: "empleados#show"
    get 'empleados/new', to: "empleados#new"
    
    root 'pages#welcome'
    
    resources :huespeds
    resources :solicituds
    resources :servicios
    resources :empleados
    
end

app/app/models/solicitud.rb
class Solicitud < ApplicationRecord
    has_many :empleados
    belongs_to :huesped, primary_key: 'cedula', foreign_key: 'huesped_id'
    belongs_to :servicio
end

app/app/controllers/solicituds_controller.rb
class SolicitudsController < ApplicationController

    def new
        @solicitud = Solicitud.new
    end
    
    def create
         @solicitud = Solicitud.new(solicitud_params)
        if @solicitud.save
            flash[:notice] = "La solicitud se creo satisfactoriamente"
            redirect_to solicitud_path(@solicitud)
        else
            render "new"
        end
    end
    
    def show 
        @solicitud = Solicitud.find(params[:id])
    end
    
    def edit
        @solicitud = Solicitud.find(params[:id])
    end 
    
    def update
        @solicitud = Solicitud.find(params[:id])
         if @solicitud.update(solicitud_params)
            flash[:notice] = "La solicitud se edito satisfactoriamente"
            redirect_to solicitud_path(@solicitud)
        else
            render "edit"
        end
    end
    
    def destroy
        @solicitud = Solicitud.find(params[:id])
        @solicitud.destroy
        flash[:notice] = "La solicitud se eliminó satisfactoriamente"
        redirect_to solicitud_path
    end
    
    def index
        @solicituds = Solicitud.all
    end
    
    private 
        def solicitud_params
         params.require(:solicitud).permit(:huesped_id,:servicio_id,:precio,:especificaciones)
        end
    
end

app/app/views/solicituds/edit.html.erb
<h1> Edicion solicitud! </h1>
<% if @solicitud.errors.any? %>
  <% @solicitud.errors.full_messages.each do |mensaje| %>
    <ul>
      <li> <%= mensaje %> </li>
    </ul>
  <% end %>
<% end %>

<%= form_for @solicitud do |f| %>
    
<p>
<%= f.label :huesped_id %><br/>
<%= f.number_field :huesped_id  %><br/>
</p>

<p>
<%= f.label :servicio_id %><br/>
<%= f.number_field :servicio_id  %><br/>
</p>

<p>
<%= f.label :precio %><br/>
<%= f.number_field :precio  %><br/>
</p>
    
<p>
<%= f.label :especificaciones %><br/>
<%= f.text_area :especificaciones %><br/>
</p>
    
        
    <p>
    <%= f.submit "Editar solicitud" %><br/>
    </p>

   <%= link_to "Volver a indice de solicitudes", solicitud_path %>
<% end %>

app/app/views/solicituds/index.html.erb
<table>
  <tr>
    <th> IDsolicitud </th><th> cedula de Usuario </th><th> IDservicio </th><th> Precio </th><th> Especificaciones </th>
  </tr>
  <% @solicituds.each do |solicitud| %>
  <tr>
    <td><%= solicitud.id %></td><td><%= solicitud.huesped_id %></td><td><%= solicitud.servicio_id %></td><td><%= solicitud.precio %></td><td><%= solicitud.especificaciones %></td>
    <td><%= link_to "Editar Solicitud", edit_solicitud_path(solicitud.id) %> </td>
    <td><%= link_to "Mostrar Solicitud", solicitud_path(solicitud) %></td>
    <td><%= link_to "Eliminar Solicitud", solicitud_path(solicitud), method: :delete, data: {confirm: "Seguro?" } %></td>
  </tr>
  <% end %>
</table>

<%= link_to "Crear solicitud", new_solicitud_path %>
<%= link_to "Pagina principal", root_path %>

app/app/views/solicituds/new.html.erb
<h1> Crear nueva solicitud! </h1>
<% if @solicitud.errors.any? %>
  <% @solicitud.errors.full_messages.each do |mensaje| %>
    <ul>
      <li> <%= mensaje %> </li>
    </ul>
  <% end %>
<% end %>

<%= form_for @solicitud do |f| %>
  
<p>
<%= f.label :huesped_id %><br/>
<%= f.number_field :huesped_id %><br/>
</p>

<p>
<%= f.label :servicio_id %><br/>
<%= f.number_field :servicio_id  %><br/>
</p>

<p>
<%= f.label :precio %><br/>
<%= f.number_field :precio  %><br/>
</p>
    
<p>
<%= f.label :especificaciones %><br/>
<%= f.text_area :especificaciones %><br/>
</p>

 <p>
<%= f.submit "Crear Nueva solicitud" %><br/>
</p>

<%= link_to "Volver a indice de solicitudes", solicituds_path %>
<% end %>

app/app/views/solicituds/show.html.erb
<h1>Solicitud Creada</h1>
<p>
  Cedula del huesped: <%= @solicitud.huesped_id %>
</p>

<p>
  Id del Servicio: <%= @solicitud.servicio_id %>
</p>

<p>
  Precio: <%= @solicitud.precio %>
</p>
<p>
  Especificaciones: <%= @solicitud.especificaciones %>
</p>


 <%= link_to "Volver a indice de solicitudes", solicituds_path %>
 <%= link_to "Editar informacion de Solicitud", edit_solicitud_path(@solicitud.id) %>