app/config/routes.rb
Rails.application.routes.draw do
    
    get 'solicituds/index', to: "solicituds#index"
    get 'solicituds/edit', to: "solicituds#edit"
    get 'solicituds/show', to: "solicituds#show"
    get 'solicituds/new', to: "solicituds#new"
    
    get 'servicios/index', to: "servicios#index"
    get 'servicios/edit', to: "servicios#edit"
    get 'servicios/show', to: "servicios#show"
    get 'servicios/new', to: "servicios#new"
    
    get 'huespeds/index', to: "huespeds#index"
    get 'huespeds/edit', to: "huespeds#edit"
    get 'huespeds/show', to: "huespeds#show"
    get 'huespeds/new', to: "huespeds#new"
    
    get 'empleados/index', to: "empleados#index"
    get 'empleados/edit', to: "empleados#edit"
    get 'empleados/show', to: "empleados#show"
    get 'empleados/new', to: "empleados#new"
    
    root 'pages#welcome'
    
    resources :huespeds
    resources :solicituds
    resources :servicios
    resources :empleados
    
end

app/app/models/huesped.rb
class Huesped < ApplicationRecord #ActiveRecord::Base
    
    has_many :solicituds, primary_key: 'cedula', foreign_key: 'huesped_id'
    has_many :servicios, through: :solicituds
    
end 

app/app/controllers/huespeds_controller.rb
class HuespedsController < ApplicationController

    def new
        @huesped = Huesped.new
    end
    
    def create
         @huesped = Huesped.new(huesped_params)
        if @huesped.save
            flash[:notice] = "El Huesped se creo satisfactoriamente"
            redirect_to huesped_path(@huesped)
        else
            render "new"
        end
    end
    
    def show 
        @huesped = Huesped.find(params[:id])
    end
    
    def edit
        @huesped = Huesped.find(params[:id])
    end 
    
    def update
        @huesped = Huesped.find(params[:id])
         if @huesped.update(huesped_params)
            flash[:notice] = "El post se creo satisfactoriamente"
            redirect_to huesped_path(@huesped)
        else
            render "edit"
        end
    end
    
    def destroy
        @huesped = Huesped.find(params[:id])
        @huesped.destroy
        flash[:notice] = "El huesped se eliminó satisfactoriamente"
        redirect_to huespeds_path
    end
    
    def index
        @huespeds = Huesped.all
    end
    
    private 
        def huesped_params
         params.require(:huesped).permit(:cedula,:nombres,:apellidos,:celular,:email,:fecha_nacimiento,:pais_origen)
        end 
end

app/app/views/huespeds/edit.html.erb
<h1> Edicion Huesped! </h1>
<% if @huesped.errors.any? %>
  <% @huesped.errors.full_messages.each do |mensaje| %>
    <ul>
      <li> <%= mensaje %> </li>
    </ul>
  <% end %>
<% end %>

<%= form_for @huesped do |f| %>
  <p>
    <%= f.label :cedula %><br/>
    <%= f.number_field :cedula  %><br/>
    </p>
    
    <p>
    <%= f.label :nombres %><br/>
    <%= f.text_field :nombres  %><br/>
    </p>
    
    <p>
    <%= f.label :apellidos %><br/>
    <%= f.text_field :apellidos  %><br/>
    </p>
    
    <p>
    <%= f.label :celular %><br/>
    <%= f.number_field :celular  %><br/>
    </p>
        
    <p>
    <%= f.label :email %><br/>
    <%= f.email_field :email %><br/>
    </p>
    
    <p>
    <%= f.label :fecha_nacimiento %><br/>
    <%= f.date_field :fecha_nacimiento %><br/>
    </p>
    
    <p>
    <%= f.label :pais_origen %><br/>
    <%= f.text_field :pais_origen %><br/>
    </p>
    
    <p>
    <%= f.submit "Editar huesped" %><br/>
    </p>

   <%= link_to "Volver a indice de huespeds", huespeds_path %>
<% end %>

app/app/views/huespeds/index.html.erb
<table>
  <tr>
    <th> ID </th><th> Cedula </th><th> Nombres </th><th> Apellidos </th><th> Celular </th><th> Email </th><th> Fecha de nacimiento </th><th> Pais de Orig </th>
  </tr>
  <% @huespeds.each do |huesped| %>
  <tr>
    <td><%= huesped.id %></td><td><%= huesped.cedula %></td><td><%= huesped.nombres %></td><td><%= huesped.apellidos %></td><td><%= huesped.celular %></td><td><%= huesped.email %></td><td><%= huesped.fecha_nacimiento %></td><td><%= huesped.pais_origen %></td>
    <td><%= link_to "Editar Post", edit_huesped_path(huesped.id) %> </td>
    <td><%= link_to "Mostrar Post", huesped_path(huesped) %></td>
    <td><%= link_to "Eliminar Post", huesped_path(huesped), method: :delete, data: {confirm: "Seguro?" } %></td>
  </tr>
  <% end %>
</table>

<%= link_to "Crear nuevo huesped", new_huesped_path %>
<%= link_to "Pagina principal", root_path %>

app/app/views/huespeds/new.html.erb
<h1>Crear un nuevo Huesped</h1>

<% if @huesped.errors.any? %>
  <% @huesped.errors.full_messages.each do |mensaje| %>
    <ul>
      <li> <%= mensaje %> </li>
    </ul>
  <% end %>
<% end %>


    <%= form_for @huesped do |f|  %>
    
    <p>
    <%= f.label :cedula %><br/>
    <%= f.number_field :cedula  %><br/>
    </p>
    
    <p>
    <%= f.label :nombres %><br/>
    <%= f.text_field :nombres  %><br/>
    </p>
    
    <p>
    <%= f.label :apellidos %><br/>
    <%= f.text_field :apellidos  %><br/>
    </p>
    
    <p>
    <%= f.label :celular %><br/>
    <%= f.number_field :celular  %><br/>
    </p>
        
    <p>
    <%= f.label :email %><br/>
    <%= f.email_field :email %><br/>
    </p>
    
    <p>
    <%= f.label :fecha_nacimiento %><br/>
    <%= f.date_field :fecha_nacimiento %><br/>
    </p>
    
    <p>
    <%= f.label :pais_origen %><br/>
    <%= f.text_field :pais_origen %><br/>
    </p>
    
    <p>
    <%= f.submit "Crear Nuevo Huesped" %><br/>
    </p>
    
    <%= link_to "Volver a indice de huespedes", huespeds_path %>
    
    <% end %>

app/app/views/huespeds/show.html.erb
<h1>Huesped Creado</h1>
<p>
  Cedula: <%= @huesped.cedula %>
</p>
<p>
  Nombres: <%= @huesped.nombres %>
</p>
<p>
  Apellidos: <%= @huesped.apellidos %>
</p>
<p>
  Celular: <%= @huesped.celular %>
</p>

<p>
  Email: <%= @huesped.email %>
</p>

<p>
  Fecha de Nacimiento: <%= @huesped.fecha_nacimiento %>
</p>
<p>
  Pais de Origen: <%= @huesped.pais_origen %>
</p>


 <%= link_to "Volver a indice de huespeds", huespeds_path %>
 <%= link_to "Editar informacion de huesped", edit_huesped_path(@huesped.id) %>