app/config/routes.rb
Rails.application.routes.draw do
    
    get 'solicituds/index', to: "solicituds#index"
    get 'solicituds/edit', to: "solicituds#edit"
    get 'solicituds/show', to: "solicituds#show"
    get 'solicituds/new', to: "solicituds#new"
    
    get 'servicios/index', to: "servicios#index"
    get 'servicios/edit', to: "servicios#edit"
    get 'servicios/show', to: "servicios#show"
    get 'servicios/new', to: "servicios#new"
    
    get 'huespeds/index', to: "huespeds#index"
    get 'huespeds/edit', to: "huespeds#edit"
    get 'huespeds/show', to: "huespeds#show"
    get 'huespeds/new', to: "huespeds#new"
    
    get 'empleados/index', to: "empleados#index"
    get 'empleados/edit', to: "empleados#edit"
    get 'empleados/show', to: "empleados#show"
    get 'empleados/new', to: "empleados#new"
    
    root 'pages#welcome'
    
    resources :huespeds
    resources :solicituds
    resources :servicios
    resources :empleados
    
end

app/app/models/servicio.rb
class Servicio < ApplicationRecord #ActiveRecord::Base
    has_many :solicituds
    has_many :huespeds, through: :solicituds
end 

app/app/models/servicios.rb
class Servicio < ApplicationRecord #ActiveRecord::Base
    has_many :huesped_servicios
    has_many :huespeds, through: :huesped_servicio
end 

app/app/controllers/servicios_controller.rb
class ServiciosController < ApplicationController

    def new
        @servicio = Servicio.new
    end
    
    def create
         @servicio = Servicio.new(servicio_params)
        if @servicio.save
            flash[:notice] = "El servicio se creo satisfactoriamente"
            redirect_to servicio_path(@servicio)
        else
            render "new"
        end
    end
    
    def show 
        @servicio = Servicio.find(params[:id])
    end
    
    def edit
        @servicio = Servicio.find(params[:id])
    end 
    
    def update
        @servicio = Servicio.find(params[:id])
         if @servicio.update(servicio_params)
            flash[:notice] = "El servicio se creo satisfactoriamente"
            redirect_to servicio_path(@servicio)
        else
            render "edit"
        end
    end
    
    def destroy
        @servicio = Servicio.find(params[:id])
        @servicio.destroy
        flash[:notice] = "El servicio se eliminó satisfactoriamente"
        redirect_to servicios_path
    end
    
    def index
        @servicios = Servicio.all
    end
    
    private 
        def servicio_params
         params.require(:servicio).permit(:nombre,:detalles,:precioBase)
        end 
end

app/app/views/servicios/edit.html.erb
<h1> Edicion Servicio! </h1>
<% if @servicio.errors.any? %>
  <% @servicio.errors.full_messages.each do |mensaje| %>
    <ul>
      <li> <%= mensaje %> </li>
    </ul>
  <% end %>
<% end %>

<%= form_for @servicio do |f| %>
  <p>
    <%= f.label :nombre %><br/>
    <%= f.text_field :nombre  %><br/>
    </p>
    
    <p>
    <%= f.label :detalles %><br/>
    <%= f.text_field :detalles  %><br/>
    </p>
    
    <p>
    <%= f.label :precioBase %><br/>
    <%= f.number_field :precioBase  %><br/>
    </p>
       
    <p>
    <%= f.submit "Editar servicio" %><br/>
    </p>

   <%= link_to "Volver a indice de servicios", servicios_path %>
<% end %>

app/app/views/servicios/index.html.erb
<table>
  <tr>
    <th> ID </th><th> Nombre </th><th> Detalles </th><th> precioBase </th>
  </tr>
  <% @servicios.each do |servicio| %>
  <tr>
    <td><%= servicio.id %></td><td><%= servicio.nombre %></td><td><%= servicio.detalles %></td><td><%= servicio.precioBase %></td>
    <td><%= link_to "Editar Servicio", edit_servicio_path(servicio.id) %> </td>
    <td><%= link_to "Mostrar Servicio", servicio_path(servicio) %></td>
    <td><%= link_to "Eliminar Servicio", servicio_path(servicio), method: :delete, data: {confirm: "Seguro?" } %></td>
  </tr>
  <% end %>
</table>

<%= link_to "Crear nuevo servicio", new_servicio_path %>
<%= link_to "Pagina principal", root_path %>

app/app/views/servicios/new.html.erb
<h1> Crear Servicio </h1>
<% if @servicio.errors.any? %>
  <% @servicio.errors.full_messages.each do |mensaje| %>
    <ul>
      <li> <%= mensaje %> </li>
    </ul>
  <% end %>
<% end %>

<%= form_for @servicio do |f| %>
  <p>
    <%= f.label :nombre %><br/>
    <%= f.text_field :nombre  %><br/>
    </p>
    
    <p>
    <%= f.label :detalles %><br/>
    <%= f.text_field :detalles  %><br/>
    </p>
    
    <p>
    <%= f.label :precioBase %><br/>
    <%= f.number_field :precioBase  %><br/>
    </p>
       
    <p>
    <%= f.submit "Crear servicio" %><br/>
    </p>

   <%= link_to "Volver a indice de servicios", servicios_path %>
<% end %>

app/app/views/servicios/show.html.erb
<h1>Servicio Creado</h1>
<p>
  Nombre: <%= @servicio.nombre %>
</p>
<p>
  Detalles: <%= @servicio.detalles %>
</p>
<p>
  Precio Base: $<%= @servicio.precioBase %>
</p>


 <%= link_to "Volver a indice de servicios", servicios_path %>
 <%= link_to "Editar informacion de servicio", edit_servicio_path(@servicio.id) %>